### ISSUE TITLE
Not all Index links has value

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/russian-laws#25]
# Intro
I talk about https://github.com/deep-foundation/russian-laws/tree/refactor/use_oop_and_children_array branch

---
# 1248 Index links of 3898 total Index links are without number value
If we run import+export test and then run the following code in browser console  
```js
const {data: spaceLinks} = await deep.select({
    type_id: await deep.id("@deep-foundation/core", "Space")
})
const sortedSpaceLinks = spaceLinks.sort((a,b) => a.id - b.id)
const lastSpaceLink = sortedSpaceLinks[sortedSpaceLinks.length-1]

const {data: indexLinks} = await deep.select({
    up: {
        tree_id: {
            _eq: await deep.id("@deep-foundation/core", "containTree")
        },
        parent_id: lastSpaceLink.id,
        link: {
            type_id: await deep.id("@deep-foundation/law", "Index"),
        }
    }
})
console.log(`indexLinks.length`, indexLinks.length)

const indexLinksWithoutValue = indexLinks.filter(link=>link.value === null)
console.log(`indexLinksWithoutValue.length`, indexLinksWithoutValue.length)

const indexLinksToIds = indexLinksWithoutValue.map(indexLink => indexLink.to_id)

const {data: linksPointedByIndexWithoutValue} = await deep.select({
    id: {
        _in: indexLinksToIds
    }
})

const typeIdsOfLinksPointedByIndexWithoutNumber = new Set(linksPointedByIndexWithoutValue.map(obj => obj.type_id));

for(const typeIdOfLinkPointedByIndexWithoutNumber of typeIdsOfLinksPointedByIndexWithoutNumber) {
    const typeNameOfLinkPointedByIndexWithoutNumber = await deep.name(typeIdOfLinkPointedByIndexWithoutNumber)
    console.log({typeNameOfLinkPointedByIndexWithoutNumber})
}
```

We will see this output:
```
indexLinks.length 3898
indexLinksWithoutValue.length 1248
{typeNameOfLinkPointedByIndexWithoutNumber: 'Clause'}
{typeNameOfLinkPointedByIndexWithoutNumber: 'Article'}
{typeNameOfLinkPointedByIndexWithoutNumber: 'Chapter'}
{typeNameOfLinkPointedByIndexWithoutNumber: 'Section'}
```
1248 index links for some reasons do not have value!

---
# Every index insert operation has according number operations and all values are numbers
If we set breakpoint to 
https://github.com/deep-foundation/russian-laws/blob/a72edd0bc38028e0fa57c98a1bdf82acddce0d08/json-to-links.ts#L169
and debug we can find out that each index insert operation has according index number value insert operation:
![image](https://github.com/deep-foundation/russian-laws/assets/66206278/8e71ae61-4f2d-4d25-846a-d3ecee0ba725)

If we run the following command to check whether all the values are number:
```
const notNumberValues = numberInsertOperationForIndexArray.map(operation => isNaN(operaiton.objects.value))
console.log({notNumberValues})
```
We will see that all values are numbers

---
# Question
What can be a reason of having 1248 index links without number value? Can this: 
https://github.com/deep-foundation/russian-laws/blob/a72edd0bc38028e0fa57c98a1bdf82acddce0d08/json-to-links.ts#L171-L182
 be a reason?

--- 
# If we do [one-by-one operation](https://github.com/deep-foundation/russian-laws/commit/04e3241ada9432a87d0835bed4f938baa5ebf3f2) - all the index links will have value, but order of result is still broken
```js
const {data: spaceLinks} = await deep.select({
    type_id: await deep.id("@deep-foundation/core", "Space")
})
const lastSpaceLink = spaceLinks[spaceLinks.length-1]

const {data: indexLinks} = await deep.select({
    up: {
        tree_id: {
            _eq: await deep.id("@deep-foundation/core", "containTree")
        },
        parent_id: lastSpaceLink.id,
        link: {
            type_id: await deep.id("@deep-foundation/law", "Index"),
        }
    }
})
console.log(`indexLinks.length`, indexLinks.length)

const indexLinksWithoutValue = indexLinks.filter(link=>link.value === null)
console.log(`indexLinksWithoutValue.length`, indexLinksWithoutValue.length)
```
```
indexLinks.length 3898
indexLinksWithoutValue.length 0
```
---

**Comment by FreePhoenix888** [comment]
I guess we need to close this issue and create a new issue at deeplinks repo. If we do serial chunk-by-chunk then all links have value. If we do every operation separately - not all links have value

**Comment by konard** [comment]
> I guess we need to close this issue and create a new issue at deeplinks repo. If we do serial chunk-by-chunk then all links have value. If we do every operation separately - not all links have value

No need to close this issue. We can just open a new one and link these issues. For `deeplinks`, we need to create a minimal reproducible example, that is simpler than this case. 10+ minutes for test to run is too much.

**Comment by FreePhoenix888** [comment]
> > I guess we need to close this issue and create a new issue at deeplinks repo. If we do serial chunk-by-chunk then all links have value. If we do every operation separately - not all links have value
> 
> No need to close this issue. We can just open a new one and link these issues. For `deeplinks`, we need to create a minimal reproducible example, that is simpler than this case. 10+ minutes for test to run is too much.

How do you see that simplified example for tests in deeplinks? Idk how to actually reproduce it. Just insert a lot of links and a lot of nubmer value for them?

**Comment by konard** [comment]
> How do you see that simplified example for tests in deeplinks? Idk how to actually reproduce it. Just insert a lot of links and a lot of nubmer value for them?

Yes, or you can reduce the size of data to just enough to reproduce
